import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />

        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-3xl text-blue-600 font-bold'> NEXT TAIL ESTORE</h1>
    </div>
  )
}
